version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: community_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: community_resources
      MYSQL_USER: community
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./springboot/database_init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - community_network

  # Spring Boot应用
  app:
    build: .
    container_name: community_app
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./files:/app/files
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: community_resources
      DB_USERNAME: root
      DB_PASSWORD: 123456
      SERVER_IP: localhost
      FILE_UPLOAD_PATH: /app/files/
    networks:
      - community_network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: community_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./files:/usr/share/nginx/html/files
    depends_on:
      - app
    networks:
      - community_network

volumes:
  mysql_data:

networks:
  community_network:
    driver: bridge
